#!/usr/bin/env ruby

inputFile = ARGV[0]
outputFile = ARGV[1]

def pather(input, output)
	started = false
	hashIndex = nil
	File.open(output, 'w') do |f|
		File.readlines(input).each do |row|
			if row.index("#")
				if started == false
					started = true
					hashIndex = row.index('#')
				else
					started = false
					for pos in hashIndex..row.index("#")-1 do
						row[pos] = "*"
					end
				end
			else 
				row[hashIndex] = "*" if started == true
			end
			f << row
		end
	end
end

pather(inputFile, outputFile)